import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Poppins } from "next/font/google";
import { Raleway } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

const poppin = Poppins({
  subsets: ["latin"],

    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-family-raleway",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${poppin.className} ${raleway.variable}`}>
        <MantineProvider>
            <Header />
            {children}
        <Footer /></MantineProvider>
      </body>
    </html>
  );
}
